[Interface]
PrivateKey = AF2xKwRxHXYnSxKbB7qt+9RXE01uUqJ/X3TjSlGctXA=
Address = 10.8.0.3/32, fdcc:ad94:bacf:61a4::cafe:3/128
MTU = 1420
DNS = 1.1.1.1, 2606:4700:4700::1111

[Peer]
PublicKey = Qu1Gp4shwj0EhDdbZnnTenKRH4EuokFNSIb/SuoYkSo=
PresharedKey = iSj/xLqKG/ssVki9mE4N+gjIivpqpvbgSFDRi963XbE=
AllowedIPs = 0.0.0.0/0, ::/0
PersistentKeepalive = 0
Endpoint = vpn.redstack.fr:51820