"""Bundle Modal worker — generate deploy/modal/worker.py from canonical sources.

Reads the four canonical worker modules from src/scrapower/worker/ and
produces a self-contained Python script at deploy/modal/worker.py for
Modal Sandbox execution. Removes relative imports (everything lives in
one file after bundling) and strips per-module __main__ blocks.

Usage:
    python scripts/bundle_modal_worker.py

After editing any of the source modules, re-run this script and commit
the regenerated deploy/modal/worker.py alongside the source changes.
"""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "src" / "scrapower" / "worker"
DST = ROOT / "deploy" / "modal" / "worker.py"

HEADER = '''\
"""Modal worker entrypoint -- AUTO-GENERATED by scripts/bundle_modal_worker.py.

Edit the canonical source modules under src/scrapower/worker/, then run:
    python scripts/bundle_modal_worker.py

Do NOT edit this file directly -- your changes will be overwritten.
"""

from __future__ import annotations

'''

MODAL_FOOTER = """
if __name__ == "__main__":
    import subprocess as _subprocess
    import sys as _sys
    import time as _time

    # Ensure runtime dependencies (whisper + yt-dlp are pulled in by whisper_runner on demand)
    _WORKER_PKGS = ["aiohttp", "faster-whisper", "yt-dlp", "wasmtime"]
    for _pkg in _WORKER_PKGS:
        try:
            __import__(_pkg.replace("-", "_"))
        except ImportError:
            _subprocess.check_call(
                [_sys.executable, "-m", "pip", "install", "-q", _pkg]
            )

    # Run with reconnect on crash
    _backoff = 5
    while True:
        try:
            main()
            break
        except Exception as _e:
            print(f"Worker crashed: {_e}")
            print(f"Restarting in {_backoff}s...")
            _time.sleep(_backoff)
            _backoff = min(_backoff * 1.5, 300)
"""


def _strip_relative_imports(code: str) -> str:
    """Remove `from .xxx import ...` lines (everything is in one file after bundle)."""
    return re.sub(r"^from \.\S+ import .*\n?", "", code, flags=re.MULTILINE)


def _strip_main_block(code: str) -> str:
    """Remove the `if __name__ == "__main__":` block (replaced by MODAL_FOOTER)."""
    return re.sub(r'\nif __name__ == "__main__":.*', "", code, flags=re.DOTALL)


def _strip_future_imports(code: str) -> str:
    """Remove module docstring and `from __future__` (already in HEADER)."""
    # Remove module docstring (triple-quoted string at top)
    code = re.sub(r'^""".*?"""\n?', "", code, flags=re.DOTALL)
    # Remove from __future__ import
    code = re.sub(r"^from __future__ import annotations\n?", "", code, flags=re.MULTILINE)
    return code


def bundle() -> None:
    files: list[tuple[str, Path]] = [
        ("runtimes/python.py", SRC / "runtimes" / "python.py"),
        ("runtimes/wasm.py", SRC / "runtimes" / "wasm.py"),
        ("loop.py", SRC / "loop.py"),
        ("entry.py", SRC / "entry.py"),
    ]

    sections: list[str] = []
    for name, path in files:
        code = path.read_text()
        code = _strip_future_imports(code)
        code = _strip_relative_imports(code)
        if name == "entry.py":
            code = _strip_main_block(code)
        sections.append(f"# === BUNDLED: scrapower/worker/{name} ===\n{code}")

    output = HEADER + "\n".join(sections) + MODAL_FOOTER
    DST.write_text(output, encoding="utf-8")
    print(f"Bundled {len(files)} modules → {DST} ({len(output)} bytes)")


if __name__ == "__main__":
    bundle()
