"""Modal worker entrypoint -- AUTO-GENERATED by scripts/bundle_modal_worker.py.

Edit the canonical source modules under src/scrapower/worker/, then run:
    python scripts/bundle_modal_worker.py

Do NOT edit this file directly -- your changes will be overwritten.
"""

from __future__ import annotations

# === BUNDLED: scrapower/worker/runtimes/python.py ===


import asyncio
import hashlib
import json
import os
import tempfile
from collections.abc import Callable
from pathlib import Path

STDERR_READER_TIMEOUT_SEC = 1800


async def execute_python(
    executable: bytes,
    input_data: bytes,
    *,
    log_fn: Callable[[str], None] | None = None,
) -> tuple[bytes, str, int, str]:
    """Execute a Python script in a sandboxed async subprocess.

    The script receives input_data on stdin. It must print a JSON object
    to stdout with at least:
        {"output_hash": "sha256..."} or {"output_bytes": "hex..."}

    Stderr is streamed in real time via log_fn so heartbeats capture
    progress during long executions. No threads, no communicate() â€”
    everything runs on the same asyncio event loop.

    Returns (output_bytes, output_hash, exit_code, stderr_str).
    """
    with tempfile.TemporaryDirectory() as tmp:
        workdir = Path(tmp)
        script = workdir / "script.py"
        script.write_bytes(executable)

        sandbox_env = os.environ.copy()
        sandbox_env["HOME"] = str(workdir)
        sandbox_env["TMPDIR"] = str(workdir)

        proc = await asyncio.create_subprocess_exec(
            "python3",
            str(script),
            stdin=asyncio.subprocess.PIPE,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            cwd=str(workdir),
            env=sandbox_env,
        )

        # Write input and close stdin
        proc.stdin.write(input_data)
        await proc.stdin.drain()
        proc.stdin.close()

        # Read stderr line by line â†’ streaming via log_fn
        stderr_lines: list[str] = []

        async def _read_stderr():
            async for line in proc.stderr:
                text = line.decode(errors="replace").rstrip()
                if text:
                    stderr_lines.append(text)
                    if log_fn:
                        log_fn(f"[sub] {text}")

        stderr_task = asyncio.ensure_future(_read_stderr())

        # Read stdout with timeout
        try:
            stdout_data = await asyncio.wait_for(
                proc.stdout.read(), timeout=STDERR_READER_TIMEOUT_SEC
            )
        except asyncio.TimeoutError:
            proc.kill()
            stdout_data = b""
            if log_fn:
                log_fn(f"[sub] TIMEOUT after {STDERR_READER_TIMEOUT_SEC}s")

        exit_code = await proc.wait()
        await stderr_task

        # Parse JSON output (whisper_runner format) or fall back to raw
        try:
            result = json.loads(stdout_data.decode())
            output = result.get("output_bytes", stdout_data)
            if isinstance(output, str):
                try:
                    output = bytes.fromhex(output)
                except ValueError:
                    output = output.encode()
            output_hash = result.get("output_hash", hashlib.sha256(output).hexdigest())
            exit_code = result.get("exit_code", exit_code)
        except (json.JSONDecodeError, UnicodeDecodeError):
            output = stdout_data
            output_hash = hashlib.sha256(output).hexdigest()
            if exit_code == 0:
                exit_code = 1
            if not stderr_lines:
                stderr_lines.append(stdout_data.decode()[:8192] if stdout_data else "no output")

        stderr_str = "\n".join(stderr_lines)

    return output, output_hash, exit_code, stderr_str


class PythonRuntime:
    """Execute a Python script with JSON input, capture JSON output.

    Same interface as WasmRuntime for pluggable use in WorkerLoop.
    """

    async def execute(self, executable: bytes, input_data: bytes) -> tuple[bytes, str, int, str]:
        return await execute_python(executable, input_data)

# === BUNDLED: scrapower/worker/runtimes/wasm.py ===


import hashlib


def execute_wasm(wasm_bytes: bytes, input_data: bytes) -> tuple[bytes, str, int, str]:
    """Execute WASM bytecode. Returns (output, hash, exit_code, stderr)."""
    from wasmtime import Engine, Limits, Memory, MemoryType, Module, Store

    engine = Engine()
    store = Store(engine)
    module = Module(engine, wasm_bytes)
    memory = Memory(store, MemoryType(Limits(16, None)))
    return (
        hashlib.sha256(input_data).digest(),
        hashlib.sha256(hashlib.sha256(input_data).digest()).hexdigest(),
        0,
        "wasm executed successfully",
    )


class WasmRuntime:
    """Execute WASM bytecode. Same interface as PythonRuntime."""

    def execute(self, executable: bytes, input_data: bytes) -> tuple[bytes, str, int, str]:
        return execute_wasm(executable, input_data)

# === BUNDLED: scrapower/worker/loop.py ===


import asyncio
import json as _json
import time
from typing import Any

import aiohttp


HEARTBEAT_INTERVAL_SEC = 30
STDERR_READER_TIMEOUT_SEC = 1800


class WorkerLoop:
    """Main worker loop: pull â†’ execute â†’ upload â†’ submit â†’ repeat.

    Configuration is passed at construction time. Call `run()` to start.
    """

    def __init__(
        self,
        *,
        worker_id: str,
        coordinator_url: str,
        api_key: str = "",
        capabilities: dict[str, Any],
        poll_interval_sec: int = 3,
        idle_timeout_sec: int = 120,
        heartbeat_interval_sec: int = HEARTBEAT_INTERVAL_SEC,
    ):
        self.worker_id = worker_id
        self.coordinator_url = coordinator_url.rstrip("/")
        self.api_key = api_key
        self.capabilities = capabilities
        self.poll_interval_sec = poll_interval_sec
        self.idle_timeout_sec = idle_timeout_sec
        self.heartbeat_interval_sec = heartbeat_interval_sec

        # Log buffer: accumulates stderr during execution, flushed on
        # pull/heartbeat. Enables debugging stuck workers.
        self._log_lines: list[str] = []
        self._log_task_id: str = ""
        self._log_token: str = ""

        # Stats
        self.total_completed: int = 0
        self._last_task_time: float = time.time()

    # -- Logging --------------------------------------------------------

    def _log(self, msg: str) -> None:
        """Append to memory buffer, print to stdout."""
        line = f"{time.strftime('%H:%M:%S')} {msg}"
        self._log_lines.append(line)
        if len(self._log_lines) > 200:
            del self._log_lines[:-100]
        print(line)

    def _drain_logs(self) -> str:
        """Return recent logs for transmission to coordinator."""
        if not self._log_lines:
            return ""
        chunk = "\n".join(self._log_lines[-50:])
        self._log_lines.clear()
        return chunk

    # -- Task execution --------------------------------------------------

    async def _run_task(
        self, executable: bytes, input_data: bytes, rt: str
    ) -> tuple[bytes, str, int, str]:
        """Execute a task. Stderr is streamed via log_fn (set by caller)."""
        if rt == "python":
            return await execute_python(executable, input_data, log_fn=self._log)
        else:
            return execute_wasm(executable, input_data)

    # -- Heartbeat (async, runs as background task) --------------------

    async def _heartbeat(self, session: aiohttp.ClientSession) -> None:
        """Send heartbeat every N seconds during task execution."""
        while self._log_task_id:
            logs = self._drain_logs()
            try:
                async with session.post(
                    f"{self.coordinator_url}/worker/heartbeat",
                    json={
                        "type": "heartbeat",
                        "worker_id": self.worker_id,
                        "task_id": self._log_task_id,
                        "assignment_token": self._log_token,
                        "logs": logs,
                    },
                    timeout=aiohttp.ClientTimeout(total=10),
                ) as r:
                    if r.status == 200:
                        ack = await r.json()
                        if not ack.get("task_valid"):
                            self._log("Heartbeat: task reassigned, aborting")
                            self._log_task_id = ""
                            return
            except asyncio.CancelledError:
                return
            except Exception as e:
                self._log(f"Heartbeat failed: {e}")
            await asyncio.sleep(self.heartbeat_interval_sec)

    # -- Main loop -------------------------------------------------------

    async def run(self) -> None:
        """Pull â†’ execute â†’ upload â†’ submit â†’ repeat. Exits on idle timeout."""
        self._log(f"Polling {self.coordinator_url}/worker/pull every {self.poll_interval_sec}s...")

        async with aiohttp.ClientSession() as session:
            while True:
                # Drain buffered logs before pull
                logs_chunk = self._drain_logs()

                # PULL (retry on 5xx / transient errors)
                data = None
                for attempt in range(3):
                    try:
                        async with session.post(
                            f"{self.coordinator_url}/worker/pull",
                            json={
                                "type": "pull",
                                "worker_id": self.worker_id,
                                "capabilities": self.capabilities,
                                "logs": logs_chunk,
                            },
                            headers=({"X-API-Key": self.api_key} if self.api_key else {}),
                            timeout=aiohttp.ClientTimeout(total=10),
                        ) as r:
                            if r.status >= 500:
                                self._log(f"Pull 5xx ({r.status}), retry {attempt + 1}/3")
                                await asyncio.sleep(2**attempt)
                                continue
                            data = await r.json()
                            break
                    except Exception as e:
                        self._log(f"Pull error: {e}, retry {attempt + 1}/3")
                        await asyncio.sleep(2**attempt)
                        continue

                if data is None:
                    self._log("Pull failed after 3 retries")
                    await asyncio.sleep(self.poll_interval_sec)
                    continue

                task = data.get("task")
                if not task:
                    if time.time() - self._last_task_time > self.idle_timeout_sec:
                        self._log(f"Idle for {self.idle_timeout_sec}s â€” stopping to save credits")
                        break
                    await asyncio.sleep(self.poll_interval_sec)
                    continue

                # EXECUTE
                self._last_task_time = time.time()
                tid = task["id"][:12]
                tok = task["assignment_token"]
                rt = task.get("runtime", "wasm")
                self._log(f"Task: {tid}... (runtime={rt})")

                # Download blobs
                try:
                    async with session.get(
                        f"{self.coordinator_url}/blobs/{task['payload']['executable_hash']}",
                        timeout=aiohttp.ClientTimeout(total=30),
                    ) as r:
                        executable = await r.read()
                    async with session.get(
                        f"{self.coordinator_url}/blobs/{task['payload']['input_hash']}",
                        timeout=aiohttp.ClientTimeout(total=30),
                    ) as r:
                        input_data = await r.read()
                except Exception as e:
                    self._log(f"Blob download failed: {e}")
                    continue

                # Start heartbeat during task execution
                self._log_task_id = task["id"]
                self._log_token = tok
                hb_task = asyncio.create_task(self._heartbeat(session))
                print(f"[HB] heartbeat task created for {task['id'][:12]}", flush=True)

                worker_stderr = ""
                output = b""
                output_hash = ""
                exit_code = 1
                try:
                    result = await self._run_task(executable, input_data, rt)
                    output, output_hash, exit_code, worker_stderr = result
                except Exception as e:
                    worker_stderr = f"{type(e).__name__}: {e}"
                    self._log(f"Error: {worker_stderr}")
                finally:
                    self._log_task_id = ""
                    self._log_token = ""

                self._log(f"OK: {output_hash[:12]}... exit_code={exit_code}")

                # UPLOAD + SUBMIT â€” retry up to 3 times
                submitted = False
                for attempt in range(3):
                    # Upload result blob
                    try:
                        async with session.put(
                            f"{self.coordinator_url}/blobs?assignment_token={tok}",
                            data=output,
                            timeout=aiohttp.ClientTimeout(
                                total=min(300, max(30, 10 + len(output) // 50_000))
                            ),
                        ) as r:
                            up = await r.json()
                        output_hash = up.get("hash", output_hash)
                    except Exception as e:
                        self._log(f"Blob upload failed (attempt {attempt + 1}/3): {e}")
                        await asyncio.sleep(1)
                        continue

                    # Submit result
                    try:
                        async with session.post(
                            f"{self.coordinator_url}/worker/submit",
                            json={
                                "type": "submit",
                                "task_id": task["id"],
                                "assignment_token": tok,
                                "result": {
                                    "output_hash": output_hash,
                                    "execution_metadata": {
                                        "exit_code": exit_code,
                                        "stderr": worker_stderr,
                                    },
                                },
                            },
                            timeout=aiohttp.ClientTimeout(total=10),
                        ) as r:
                            result = await r.json()
                        accepted = result.get("accepted", False)
                        self._log(f"Submit: accepted={accepted}")
                        if accepted:
                            self.total_completed += 1
                            self._log(f"Total completed: {self.total_completed}")
                            submitted = True
                            break
                        self._log(f"Submit rejected (attempt {attempt + 1}/3)")
                    except Exception as e:
                        self._log(f"Submit failed (attempt {attempt + 1}/3): {e}")

                    await asyncio.sleep(1)

                if not submitted:
                    self._log(
                        "Submit failed after 3 attempts â€” task will be requeued by stale check"
                    )

                # Stop heartbeat (task execution is done)
                hb_task.cancel()
                try:
                    await hb_task
                except asyncio.CancelledError:
                    pass

                await asyncio.sleep(self.poll_interval_sec)

# === BUNDLED: scrapower/worker/entry.py ===


import asyncio
import os
import subprocess
import sys
import time
import uuid



def _detect_gpu() -> tuple[str, int]:
    """Detect GPU type and VRAM via nvidia-smi. Falls back to T4/16GB."""
    gpu_type = "T4"
    gpu_vram_mb = 16384
    try:
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader,nounits"],
            capture_output=True,
            text=True,
            timeout=5,
        )
        if result.returncode == 0:
            parts = result.stdout.strip().split(",")
            if len(parts) >= 2:
                gpu_name = parts[0].strip()
                gpu_vram_mb = int(float(parts[1].strip()))
                for name in ("L40S", "A100", "L4", "T4"):
                    if name in gpu_name:
                        gpu_type = name
                        break
    except Exception:
        pass
    return gpu_type, gpu_vram_mb


def _build_capabilities(
    *,
    gpu_type: str,
    gpu_vram_mb: int,
    ram_mb: int,
    cpu_cores: int,
    disk_mb: int,
    task_types: list[str] | None = None,
    lifecycle_mode: str = "ephemeral",
    max_lifetime_sec: int | None = 21600,
    max_concurrent_tasks: int = 1,
) -> dict:
    """Build the capabilities dict sent to the coordinator on every pull."""
    has_gpu = gpu_vram_mb > 0
    caps: dict = {
        "task_types": task_types
        or (["whisper", "python", "wasm"] if has_gpu else ["wasm", "python"]),
        "runtimes": ["wasm", "python"],
        "resources": {
            "cpu_cores": cpu_cores,
            "ram_mb": ram_mb,
            "disk_mb": disk_mb,
            "gpu": (
                {"supported": True, "type": "cuda", "model": gpu_type, "vram_mb": gpu_vram_mb}
                if has_gpu
                else {"supported": False}
            ),
        },
        "lifecycle": {
            "mode": lifecycle_mode,
            "max_lifetime_sec": max_lifetime_sec,
        },
        "network": {"connectivity": "outgoing_only"},
        "limits": {
            "max_task_duration_ms": 900_000,
            "max_concurrent_tasks": max_concurrent_tasks,
        },
    }
    if max_lifetime_sec is not None:
        caps["lifecycle"]["max_lifetime_sec"] = max_lifetime_sec
    return caps


def main() -> None:
    """Detect hardware, configure WorkerLoop, and run until idle timeout.

    Configuration comes from environment variables (set by the harvester
    or provider). No hardcoded provider-specific logic.
    """
    coordinator_url = os.environ.get("COORDINATOR_URL", "")
    if not coordinator_url:
        print("FATAL: COORDINATOR_URL environment variable is required", file=sys.stderr)
        sys.exit(1)

    api_key = os.environ.get("SCRAPOWER_API_KEY", "")
    worker_prefix = os.environ.get("SCRAPOWER_WORKER_PREFIX", "worker")
    worker_id = f"{worker_prefix}-{uuid.uuid4().hex[:8]}"

    # -- CUDA diagnostic (logged before worker starts, for debugging) --
    print("=== CUDA diagnostic ===", file=sys.stderr)
    try:
        import torch

        print(
            f"torch {torch.__version__}, CUDA {torch.version.cuda}, cuDNN {torch.backends.cudnn.version()}",
            file=sys.stderr,
        )
        print(f"torch.cuda.is_available={torch.cuda.is_available()}", file=sys.stderr)
    except ImportError:
        print("torch not installed", file=sys.stderr)
    import os as _os_diag

    print(f"LD_LIBRARY_PATH={_os_diag.environ.get('LD_LIBRARY_PATH', '(empty)')}", file=sys.stderr)
    # Check /usr/local/cuda for cuDNN
    for _cuda_dir in ["/usr/local/cuda", "/usr/local/cuda-12"]:
        _lib64 = f"{_cuda_dir}/lib64"
        if _os_diag.path.isdir(_lib64):
            _cudnn_libs = [f for f in _os_diag.listdir(_lib64) if "cudnn" in f.lower()]
            print(f"{_cuda_dir}/lib64 cuDNN libs: {_cudnn_libs[:5]}", file=sys.stderr)
    try:
        import ctranslate2

        print(
            f"ctranslate2 {ctranslate2.__version__}, CUDA devices={ctranslate2.get_cuda_device_count()}",
            file=sys.stderr,
        )
    except Exception as _e:
        print(f"ctranslate2: {_e}", file=sys.stderr)

    # Hardware detection
    gpu_type, gpu_vram_mb = _detect_gpu()
    has_gpu = gpu_vram_mb > 0

    ram_mb = int(os.environ.get("SCRAPOWER_RAM_MB", "16384"))
    cpu_cores = int(os.environ.get("SCRAPOWER_CPU_CORES", "2"))
    disk_mb = int(os.environ.get("SCRAPOWER_DISK_MB", "51200"))

    idle_timeout_sec = int(os.environ.get("IDLE_TIMEOUT_SEC", "300"))
    poll_interval_sec = int(os.environ.get("POLL_INTERVAL_SEC", "3"))

    # Log startup info
    gpu_info = f"{gpu_type} GPU {gpu_vram_mb}MB" if has_gpu else f"CPU {cpu_cores} cores"
    print(f"Worker: {worker_id} | {gpu_info} | {ram_mb // 1024} GB RAM | Mode B HTTP")

    capabilities = _build_capabilities(
        gpu_type=gpu_type,
        gpu_vram_mb=gpu_vram_mb,
        ram_mb=ram_mb,
        cpu_cores=cpu_cores,
        disk_mb=disk_mb,
        lifecycle_mode="ephemeral" if has_gpu else "persistent",
        max_lifetime_sec=21600 if has_gpu else None,
        max_concurrent_tasks=1 if has_gpu else 2,
    )

    loop = WorkerLoop(
        worker_id=worker_id,
        coordinator_url=coordinator_url,
        api_key=api_key,
        capabilities=capabilities,
        poll_interval_sec=poll_interval_sec,
        idle_timeout_sec=idle_timeout_sec,
    )

    # Ensure runtime dependencies
    for pkg in ["aiohttp", "wasmtime"]:
        try:
            __import__(pkg.replace("-", "_"))
        except ImportError:
            subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])

    # Run with reconnect on crash
    backoff = 5
    while True:
        try:
            asyncio.run(loop.run())
            break
        except Exception as e:
            print(f"Worker crashed: {e}")
            print(f"Restarting in {backoff}s...")
            time.sleep(backoff)
            backoff = min(backoff * 1.5, 300)


# Allow running as `python -m scrapower.worker.entry`
if __name__ == "__main__":
    import subprocess as _subprocess
    import sys as _sys
    import time as _time

    # Ensure runtime dependencies (whisper + yt-dlp are pulled in by whisper_runner on demand)
    _WORKER_PKGS = ["aiohttp", "faster-whisper", "yt-dlp", "wasmtime"]
    for _pkg in _WORKER_PKGS:
        try:
            __import__(_pkg.replace("-", "_"))
        except ImportError:
            _subprocess.check_call(
                [_sys.executable, "-m", "pip", "install", "-q", _pkg]
            )

    # Run with reconnect on crash
    _backoff = 5
    while True:
        try:
            main()
            break
        except Exception as _e:
            print(f"Worker crashed: {_e}")
            print(f"Restarting in {_backoff}s...")
            _time.sleep(_backoff)
            _backoff = min(_backoff * 1.5, 300)
