"""Modal worker entrypoint — bundled from scrapower.worker package.

This file is generated by ModalHarvester._bundle_worker() which reads
the canonical worker modules from src/scrapower/worker/ and produces
a self-contained script. Edit the source modules, not this file.
"""

# === BUNDLED: scrapower/worker/runtimes/python.py ===
import hashlib as _hashlib
import json as _json
import os as _os
import subprocess as _subprocess
import tempfile as _tempfile
from pathlib import Path as _Path


def _worker_execute_python(executable, input_data, *, log_fn=None):
    with _tempfile.TemporaryDirectory() as tmp:
        workdir = _Path(tmp)
        script = workdir / "script.py"
        script.write_bytes(executable)
        sandbox_env = {
            "PATH": "/usr/bin:/usr/local/bin",
            "HOME": str(workdir),
            "TMPDIR": str(workdir),
            "WG_PROXY": _os.environ.get("WG_PROXY", ""),
        }
        proc = _subprocess.Popen(
            ["python3", str(script)],
            stdin=_subprocess.PIPE,
            stdout=_subprocess.PIPE,
            stderr=_subprocess.PIPE,
            cwd=str(workdir),
            env=sandbox_env,
        )
        try:
            stdout_data, stderr_data = proc.communicate(input=input_data, timeout=600)
        except _subprocess.TimeoutExpired:
            proc.kill()
            stdout_data, stderr_data = proc.communicate()
            if log_fn:
                log_fn("[sub] TIMEOUT after 600s")
        exit_code = proc.returncode
        stderr_str = stderr_data.decode(errors="replace") if stderr_data else ""
        if log_fn:
            for line in stderr_str.split("\n"):
                if line.strip():
                    log_fn(f"[sub] {line.strip()}")
        try:
            result = _json.loads(stdout_data.decode())
            output = result.get("output_bytes", stdout_data)
            if isinstance(output, str):
                try:
                    output = bytes.fromhex(output)
                except ValueError:
                    output = output.encode()
            output_hash = result.get("output_hash", _hashlib.sha256(output).hexdigest())
            exit_code = result.get("exit_code", exit_code)
        except (_json.JSONDecodeError, UnicodeDecodeError):
            output = stdout_data
            output_hash = _hashlib.sha256(output).hexdigest()
            if exit_code == 0:
                exit_code = 1
            if not stderr_str:
                stderr_str = stdout_data.decode()[:8192] if stdout_data else "no output"
    return output, output_hash, exit_code, stderr_str


# === BUNDLED: scrapower/worker/runtimes/wasm.py ===
def _worker_execute_wasm(wasm_bytes, input_data):
    from wasmtime import Engine, Limits, Memory, MemoryType, Module, Store

    engine = Engine()
    store = Store(engine)
    module = Module(engine, wasm_bytes)
    memory = Memory(store, MemoryType(Limits(16, None)))
    return (
        _hashlib.sha256(input_data).digest(),
        _hashlib.sha256(_hashlib.sha256(input_data).digest()).hexdigest(),
        0,
        "wasm executed successfully",
    )


# === BUNDLED: scrapower/worker/loop.py + entry.py ===
import asyncio
import concurrent.futures
import io
import sys
import time as _time
import urllib.request
import uuid as _uuid

import aiohttp

_COORDINATOR_URL = _os.environ.get("COORDINATOR_URL", "")
if not _COORDINATOR_URL:
    print("FATAL: COORDINATOR_URL is required", file=sys.stderr)
    sys.exit(1)
_API_KEY = _os.environ.get("SCRAPOWER_API_KEY", "")
_WORKER_ID = f"modal-{_uuid.uuid4().hex[:8]}"

# GPU detection
_GPU_TYPE, _GPU_VRAM_MB = "T4", 16384
try:
    r = _subprocess.run(
        ["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader,nounits"],
        capture_output=True,
        text=True,
        timeout=5,
    )
    if r.returncode == 0:
        parts = r.stdout.strip().split(",")
        if len(parts) >= 2:
            _GPU_TYPE = parts[0].strip()
            _GPU_VRAM_MB = int(float(parts[1].strip()))
            for n in ("L40S", "A100", "L4", "T4"):
                if n in _GPU_TYPE:
                    _GPU_TYPE = n
                    break
except Exception:
    pass

_RAM_MB = int(_os.environ.get("SCRAPOWER_RAM_MB", "30720"))
_CPU_CORES = int(_os.environ.get("SCRAPOWER_CPU_CORES", "4"))
_IDLE_TIMEOUT_SEC = int(_os.environ.get("IDLE_TIMEOUT_SEC", "120"))
_POLL_INTERVAL_SEC = 3

print(
    f"Worker: {_WORKER_ID} | {_GPU_TYPE} GPU {_GPU_VRAM_MB}MB | {_RAM_MB // 1024} GB RAM | Mode B HTTP"
)

_CAPABILITIES = {
    "task_types": ["whisper", "python", "wasm"],
    "runtimes": ["wasm", "python"],
    "resources": {
        "cpu_cores": _CPU_CORES,
        "ram_mb": _RAM_MB,
        "disk_mb": 102400,
        "gpu": {"supported": True, "type": "cuda", "model": _GPU_TYPE, "vram_mb": _GPU_VRAM_MB},
    },
    "lifecycle": {"mode": "ephemeral", "max_lifetime_sec": 21600},
    "network": {"connectivity": "outgoing_only"},
    "limits": {"max_task_duration_ms": 900000, "max_concurrent_tasks": 1},
}

# Log buffer
_LOG_LINES = []
_LOG_TASK_ID = ""
_LOG_TOKEN = ""
_TOTAL_COMPLETED = 0
_last_task_time = _time.time()


def _log(msg):
    line = f"{_time.strftime('%H:%M:%S')} {msg}"
    _LOG_LINES.append(line)
    if len(_LOG_LINES) > 200:
        del _LOG_LINES[:-100]
    print(line)


def _drain_logs():
    if not _LOG_LINES:
        return ""
    chunk = "\n".join(_LOG_LINES[-50:])
    _LOG_LINES.clear()
    return chunk


def _run_task_sync(executable, input_data, rt):
    stderr_capture = io.StringIO()
    old_stderr, sys.stderr = sys.stderr, stderr_capture
    try:
        result = (
            _worker_execute_python(executable, input_data, log_fn=_log)
            if rt == "python"
            else _worker_execute_wasm(executable, input_data)
        )
        captured = stderr_capture.getvalue()
        if captured:
            for line in captured.split("\n"):
                if line.strip():
                    _log(f"[sub] {line.strip()}")
        return result
    finally:
        sys.stderr = old_stderr


def _heartbeat_sync():
    global _LOG_TASK_ID
    while _LOG_TASK_ID:
        logs = _drain_logs()
        print(f"[HB] sending heartbeat for {_LOG_TASK_ID[:12]}...", flush=True)
        try:
            data = _json.dumps(
                {
                    "type": "heartbeat",
                    "worker_id": _WORKER_ID,
                    "task_id": _LOG_TASK_ID,
                    "assignment_token": _LOG_TOKEN,
                    "logs": logs,
                }
            ).encode()
            req = urllib.request.Request(
                f"{_COORDINATOR_URL}/worker/heartbeat",
                data=data,
                headers={"Content-Type": "application/json"},
            )
            with urllib.request.urlopen(req, timeout=10) as resp:
                ack = _json.loads(resp.read())
            if not ack.get("task_valid"):
                _log("Heartbeat: task reassigned, aborting")
                _LOG_TASK_ID = ""
        except Exception as e:
            _log(f"Heartbeat failed: {e}")
        _time.sleep(30)


async def _heartbeat(session):
    loop = asyncio.get_running_loop()
    with concurrent.futures.ThreadPoolExecutor(max_workers=1) as pool:
        await loop.run_in_executor(pool, _heartbeat_sync)


async def run():
    global _TOTAL_COMPLETED, _last_task_time, _LOG_TASK_ID, _LOG_TOKEN
    async with aiohttp.ClientSession() as session:
        _log(f"Polling {_COORDINATOR_URL}/worker/pull every {_POLL_INTERVAL_SEC}s...")
        while True:
            logs_chunk = _drain_logs()
            data = None
            for attempt in range(3):
                try:
                    async with session.post(
                        f"{_COORDINATOR_URL}/worker/pull",
                        json={
                            "type": "pull",
                            "worker_id": _WORKER_ID,
                            "capabilities": _CAPABILITIES,
                            "logs": logs_chunk,
                        },
                        headers={"X-API-Key": _API_KEY} if _API_KEY else {},
                        timeout=aiohttp.ClientTimeout(total=10),
                    ) as r:
                        if r.status >= 500:
                            _log(f"Pull 5xx ({r.status}), retry {attempt + 1}/3")
                            await asyncio.sleep(2**attempt)
                            continue
                        data = await r.json()
                        break
                except Exception as e:
                    _log(f"Pull error: {e}, retry {attempt + 1}/3")
                    await asyncio.sleep(2**attempt)
            if data is None:
                _log("Pull failed after 3 retries")
                await asyncio.sleep(_POLL_INTERVAL_SEC)
                continue
            task = data.get("task")
            if not task:
                if _time.time() - _last_task_time > _IDLE_TIMEOUT_SEC:
                    _log(f"Idle for {_IDLE_TIMEOUT_SEC}s - stopping")
                    break
                await asyncio.sleep(_POLL_INTERVAL_SEC)
                continue
            _last_task_time = _time.time()
            tid, tok, rt = task["id"][:12], task["assignment_token"], task.get("runtime", "wasm")
            _log(f"Task: {tid}... (runtime={rt})")
            try:
                async with session.get(
                    f"{_COORDINATOR_URL}/blobs/{task['payload']['executable_hash']}",
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as r:
                    executable = await r.read()
                async with session.get(
                    f"{_COORDINATOR_URL}/blobs/{task['payload']['input_hash']}",
                    timeout=aiohttp.ClientTimeout(total=30),
                ) as r:
                    input_data = await r.read()
            except Exception as e:
                _log(f"Blob download failed: {e}")
                continue
            _LOG_TASK_ID, _LOG_TOKEN = task["id"], tok
            hb_task = asyncio.create_task(_heartbeat(session))
            print(f"[HB] heartbeat task created for {task['id'][:12]}", flush=True)
            worker_stderr, output, output_hash, exit_code = "", b"", "", 1
            try:
                loop = asyncio.get_running_loop()
                result = await loop.run_in_executor(
                    None, _run_task_sync, executable, input_data, rt
                )
                output, output_hash, exit_code, worker_stderr = result
            except Exception as e:
                worker_stderr = f"{type(e).__name__}: {e}"
                _log(f"Error: {worker_stderr}")
            finally:
                _LOG_TASK_ID = ""
                _LOG_TOKEN = ""
            _log(f"OK: {output_hash[:12]}... exit_code={exit_code}")
            submitted = False
            for attempt in range(3):
                try:
                    async with session.put(
                        f"{_COORDINATOR_URL}/blobs?assignment_token={tok}",
                        data=output,
                        timeout=aiohttp.ClientTimeout(
                            total=min(300, max(30, 10 + len(output) // 50_000))
                        ),
                    ) as r:
                        up = await r.json()
                    output_hash = up.get("hash", output_hash)
                except Exception as e:
                    _log(f"Blob upload failed (attempt {attempt + 1}/3): {e}")
                    await asyncio.sleep(1)
                    continue
                try:
                    async with session.post(
                        f"{_COORDINATOR_URL}/worker/submit",
                        json={
                            "type": "submit",
                            "task_id": task["id"],
                            "assignment_token": tok,
                            "result": {
                                "output_hash": output_hash,
                                "execution_metadata": {
                                    "exit_code": exit_code,
                                    "stderr": worker_stderr,
                                },
                            },
                        },
                        timeout=aiohttp.ClientTimeout(total=10),
                    ) as r:
                        result = await r.json()
                    accepted = result.get("accepted", False)
                    _log(f"Submit: accepted={accepted}")
                    if accepted:
                        _TOTAL_COMPLETED += 1
                        _log(f"Total completed: {_TOTAL_COMPLETED}")
                        submitted = True
                        break
                    _log(f"Submit rejected (attempt {attempt + 1}/3)")
                except Exception as e:
                    _log(f"Submit failed (attempt {attempt + 1}/3): {e}")
                await asyncio.sleep(1)
            if not submitted:
                _log("Submit failed after 3 attempts")
            hb_task.cancel()
            try:
                await hb_task
            except asyncio.CancelledError:
                pass
            await asyncio.sleep(_POLL_INTERVAL_SEC)


if __name__ == "__main__":
    for pkg in ["aiohttp", "faster-whisper", "yt-dlp"]:
        try:
            __import__(pkg.replace("-", "_"))
        except ImportError:
            _subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", pkg])
    backoff = 5
    while True:
        try:
            asyncio.run(run())
            break
        except Exception as e:
            print(f"Worker crashed: {e}")
            print(f"Restarting in {backoff}s...")
            _time.sleep(backoff)
            backoff = min(backoff * 1.5, 300)
